### ISSUE TITLE
Strikethrough doesnt work in the theme

### ISSUE THREAD

**Issue by shreelock** [vishvanath45/vishvanath45.github.io#4]
> Currently, I am ~doing~ completed Internship

**Comment by vishvanath45** [comment]
fixed.  

let server update itself in some time.

**Comment by shreelock** [comment]
this strikethrough doesnt look good. maybe its the font's design. 
<img width="189" alt="image" src="https://user-images.githubusercontent.com/830611/43789732-b11679e2-9a3e-11e8-8472-f623e359846f.png">

**Comment by vishvanath45** [comment]
unable to access image. :/

**Comment by shreelock** [comment]
https://user-images.githubusercontent.com/830611/43789732-b11679e2-9a3e-11e8-8472-f623e359846f.png

**Comment by vishvanath45** [comment]
Here, it is rendered fine, [see this](https://i.imgur.com/BX52Kq7.png)

**Comment by shreelock** [comment]
I see, maybe browser dependent, then its alright
