### ISSUE TITLE
Theme update

### ISSUE THREAD

**Issue by shreelock** [vishvanath45/vishvanath45.github.io#6]
Think of using a more soothing, clean and readable theme?

**Comment by vishvanath45** [comment]
Okay!, time to revamp whole page.

**Comment by shreelock** [comment]
think of a .in domain name and lmk

**Comment by shreelock** [comment]
can be something that you use as ur github and  linkedin username

**Comment by vishvanath45** [comment]
Checkout theme now?

**Comment by shreelock** [comment]
looks good, the italics need a bigger font, since italicising them makes them a bit shorted
